# url: https://blog.susnjar.net
# theme: jekyll-theme-cayman
theme: minima
title: Cogitatorium
author: Aleksandar Susnjar
url-pretty: blog.susnjar.net
title-on-all-pages: true


# titles_from_headings:
#   enabled: true
#   strip_title: true
#   collections: true
  
# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# lsi: false
safe: false
# source: blog/
incremental: false
highlighter: rouge
gist:
  noscript: false
  
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

paginate: 12

plugins:
  - jekyll-paginate
  - jekyll-sitemap
