url: https://blog.susnjar.net
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
lsi: false
safe: true
source: blog
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
